mongodb:
  host: mongodb

server:
  port: 9090
  servlet:
    path: /s
    context-path: /auth-server

secret: 123456

authentication:
  code:
    expiration: 100
  client-id: my-client-id

register:
  server:
    url: http://kjdkjd.com

spring:
  jersey:
    type: filter
