mongodb:
  host: mongodb

server:
  port: 9090
  servlet:
    path: /s
    context-path: /auth-server

favorite:
  ads:
    security:
      permitted:
        path: /probe,/s/health,/s/info,/application.wadl,/swagger,/swagger.json,/swagger.yaml,/v1/admin/users/**

spring:
  jersey:
    type: filter
