version: '3.3'

services:

  nginx:
   restart: always
   container_name: my-nginx
   image: nginx:1.13
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./../utils/nginx/conf.d:/etc/nginx/conf.d

  mongodb:
    restart: always
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /Volumes/Zaka Drive/Developer/mongo/data:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles

  app:
    restart: always
    container_name: favorite_ads_app
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
      - nginx
      - mongodb